[SETTINGS]
# Set the path to the location containing your certificates (root, private, claim certificate)
SECURE_CERT_PATH = /usr/share/blackbird/ifm-barcode-reader/secrets

# Specify the names for the root cert, provisioning claim cert, and the private key.
ROOT_CERT = AmazonRootCA1.pem
CLAIM_CERT = claim_certificate.pem.crt
SIGN_KEY = sign_private.pem
SECURE_KEY = claim_private.pem.key

# Set the name of your IoT Endpoint
IOT_ENDPOINT = a3f8k0ccx04zas-ats.iot.eu-west-1.amazonaws.com

# Include the name for the provisioning template that was created in IoT Core
PRODUCTION_TEMPLATE = barcodeProvisioningTemplate
CERT_ROTATION_TEMPLATE = cert_rotation

# Set the time (in minutes) before retrying provisioning
PROVISION_RETRY_BACKOFF = 10

# bootstrap.sh will append with device uuid at the end of this file: